services:
  furigana-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./jmdict.db:/app/jmdict.db:ro
      - ./jmdict_common_eng.json:/app/jmdict_common_eng.json:ro
      - ./kanji_jlpt.json:/app/kanji_jlpt.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



networks:
  default:
    name: furigana-network